### ISSUE TITLE
python 3.12 wheel

### ISSUE THREAD

**Issue by quetil** [spotfiresoftware/spotfire-python#66]
Hi, could someone provide a wheel for python 3.12 ? (windows and linux)
I didn't manage to install it with `pip install -e .` nor `python -m build`.

Thank you in advance !

**Comment by bbassett-tibco** [comment]
Hey, @quetil! We're currently targeting the next release (2.2.0) for shipping wheels for Python 3.12.  Unfortunately, current versions will not compile for 3.12 (due to the removal of deprecated `Py_UNICODE` functions); we've already fixed this in 504207b, and it's already a part of our Actions CI workflows.
